CREATE TABLE Estado
(
 IdEstado INT NOT NULL AUTO_INCREMENT,
 DescEstado VARCHAR(50) NOT NULL,
 CONSTRAINT PK_ESTADO PRIMARY KEY (IdEstado)
);

CREATE TABLE Sala
(
 IdSala INT NOT NULL AUTO_INCREMENT,
 DescSala VARCHAR(50) NOT NULL,
 Asientos INT NOT NULL,
 IdEstado INT NOT NULL,
 CONSTRAINT PK_SALA PRIMARY KEY (IdSala),
 CONSTRAINT FK_SALA_ESTADO FOREIGN KEY (IdEstado) REFERENCES ESTADO(IdEstado)
);


 CREATE TABLE Pelicula
(
 IdPelicula 	INT NOT NULL AUTO_INCREMENT,
 Titulo 		VARCHAR(50) NOT NULL,
 Duracion 		INT NOT NULL,
 Genero			VARCHAR(50) NOT NULL,
 Clasificacion	VARCHAR(50)NOT NULL,
 Formato 		VARCHAR(40) NOT NULL,
 IdEstado		INT NOT NULL,
 CONSTRAINT PK_PELICULA PRIMARY KEY (IdPelicula),
 CONSTRAINT FK_PELICULA_ESTADO FOREIGN KEY (IdEstado) REFERENCES ESTADO(IdEstado)
);


CREATE TABLE Asiento
(
 IdAsiento INT NOT NULL AUTO_INCREMENT,
 NroAsiento INT NOT NULL,
 IdSala INT NOT NULL,
 IdEstado INT NOT NULL,
 CONSTRAINT PK_ASIENTO PRIMARY KEY (IdAsiento),
 CONSTRAINT FK_ASIENTO_SALA FOREIGN KEY (IdSala) REFERENCES SALA(IdSala),
 CONSTRAINT FK_ASIENTO_ESTADO FOREIGN KEY (IdEstado) REFERENCES ESTADO(IdEstado)
);

CREATE TABLE Cliente
(
 IdCliente INT NOT NULL AUTO_INCREMENT,
 NomCliente VARCHAR(50) NOT NULL,
 ApeCliente VARCHAR(50) NOT NULL,
 DniCliente CHAR(8) NULL,
 CONSTRAINT PK_CLIENTE PRIMARY KEY (IdCliente)
);

CREATE TABLE Cartelera
(
 IdCartelera INT NOT NULL AUTO_INCREMENT,
 IdPelicula INT NOT NULL,
 IdSala INT NOT NULL,
 HoraInicio TIME NOT NULL,
 HoraFin TIME NOT NULL,
 Fecha DATE NOT NULL,
 IdEstado INT NOT NULL,
 CONSTRAINT PK_CARTELERA PRIMARY KEY (IdCartelera),
 CONSTRAINT FK_CARTELERA_PELICULA FOREIGN KEY (IdPelicula) REFERENCES PELICULA(IdPelicula),
 CONSTRAINT FK_CARTELERA_SALA FOREIGN KEY (IdSala) REFERENCES SALA(IdSala),
 CONSTRAINT FK_CARTELERA_ESTADO FOREIGN KEY (IdEstado) REFERENCES ESTADO(IdEstado)
);

CREATE TABLE RegistroAsiento
(
 IdRasiento INT NOT NULL AUTO_INCREMENT,
 IdCartelera INT NOT NULL,
 NroAsiento INT NOT NULL,
 CONSTRAINT PK_RASIENTO PRIMARY KEY (IdRasiento),
 CONSTRAINT FK_RASIENTO_CARTELERA FOREIGN KEY (IdCartelera) REFERENCES CARTELERA(IdCartelera)
);
CREATE TABLE AsientoCliente
(
 IdAcliente INT NOT NULL AUTO_INCREMENT,
 IdRasiento INT NOT NULL,
 IdCliente INT NOT NULL,
 CONSTRAINT PK_ACLIENTE PRIMARY KEY (IdAcliente),
 CONSTRAINT FK_ACLIENTE_RCLIENTE FOREIGN KEY (IdRasiento) REFERENCES REGISTROASIENTO(IdRasiento),
 CONSTRAINT FK_ACLIENTE_CLIENTE FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente)

);
CREATE TABLE Empleado
(
 IdEmpleado INT NOT NULL AUTO_INCREMENT,
 Nombre VARCHAR(50) NOT NULL,
 Apellido VARCHAR(50) NOT NULL,
 FechaContrat DATE NOT NULL,
 IdEstado INT NOT NULL,
 CONSTRAINT PK_EMPLEADO PRIMARY KEY (IdEmpleado),
 CONSTRAINT FK_EMPLEADO_ESTADO FOREIGN KEY (IdEstado) REFERENCES ESTADO(IdEstado)
);

CREATE TABLE Ticket
(
 IdTicket INT NOT NULL AUTO_INCREMENT,
 Tipo VARCHAR(80)NOT NULL,
 Descripcion VARCHAR(200) NOT NULL,
 Precio DECIMAL(10,2) NOT NULL,
 IdEstado INT NOT NULL,
 CONSTRAINT PK_TICKET PRIMARY KEY (IdTicket),
 CONSTRAINT FK_TICKET_ESTADO FOREIGN KEY (IdEstado) REFERENCES ESTADO(IdEstado)
);

CREATE TABLE Venta
(
 IdVenta INT NOT NULL AUTO_INCREMENT,
 IdCliente INT NOT NULL,
 IdCartelera INT NOT NULL,
 IdEmpleado INT NOT NULL,
 Fecha DATE NOT NULL,
 Asientos VARCHAR(20) NOT NULL,
 Tpago VARCHAR(50) NOT NULL,
 Promocion VARCHAR(80) NOT NULL,
 Descuento DECIMAL(10,2) NOT NULL,
 IdEstado INT NOT NULL,
 CONSTRAINT PK_VENTA PRIMARY KEY (IdVenta),
 CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente),
 CONSTRAINT FK_VENTA_CARTELERA FOREIGN KEY (IdCartelera) REFERENCES CARTELERA(IdCartelera),
 CONSTRAINT FK_VENTA_EMPLEADO FOREIGN KEY (IdEmpleado) REFERENCES EMPLEADO(IdEmpleado),
 CONSTRAINT FK_VENTA_ESTADO FOREIGN KEY (IdEstado) REFERENCES ESTADO(IdEstado)
);

CREATE TABLE DetalleVenta
(
 IdDventa INT NOT NULL AUTO_INCREMENT,
 IdVenta INT NOT NULL,
 Descripcion VARCHAR(100) NOT NULL,
 Cantidad INT NOT NULL,
 Precio DECIMAL(10,2) NOT NULL,
 CONSTRAINT PK_DVENTA PRIMARY KEY (IdDventa),
 CONSTRAINT FK_DVENTA_VENTA FOREIGN KEY (IdVenta) REFERENCES VENTA(IdVenta)
);

CREATE TABLE Promocion
(
 IdPromocion INT NOT NULL AUTO_INCREMENT,
 Nombre VARCHAR(80) NOT NULL,
 Descuento DECIMAL (10,2) NOT NULL,
 BaseTicket BIT NOT NULL,
 IdEstado INT NOT NULL,
 CONSTRAINT PK_PROMOCION PRIMARY KEY (IdPromocion),
 CONSTRAINT FK_PROMOCION_ESTADO FOREIGN KEY (IdEstado) REFERENCES ESTADO(IdEstado)
);

CREATE TABLE ProgrPromocion
(
 IdPpromocion INT NOT NULL AUTO_INCREMENT,
 Fecha DATE NOT NULL,
 Promocion VARCHAR(80) NOT NULL,
 IdEstado INT NOT NULL,
 CONSTRAINT PK_PPROMOCION PRIMARY KEY (IdPpromocion),
 CONSTRAINT FK_PPROMOCION_ESTADO FOREIGN KEY (IdEstado) REFERENCES ESTADO(IdEstado)
);



